### ISSUE TITLE
Protocol 'Any' as a type cannot conform to 'AnyArgument'

### ISSUE THREAD

**Issue by calitb** [andrew-levy/react-native-userdefaults#1]
Xcode 13.4.1
Expo 46.0.9

Steps to duplicate:
1. Add plugin to project
2. expo prebuild
3. npx expo run:ios   

I get and error in this line: https://github.com/andrew-levy/react-native-userdefaults/blob/main/ios/ReactNativeUserDefaultsModule.swift#L8

I was able to make it work by switching `Any?` with `String?` in a repo fork

**Comment by andrew-levy** [comment]
Hey @calitb, do you have a minimal repo you could share with me or a detailed code example of how you're using it? I just installed it into a new project and tested our getting and setting values of many different types and it worked fine. 

I haven't upgraded to expo 46 on my personal computer yet, so maybe the api changed? It's a new and experimental api.

**Comment by calitb** [comment]
attaching the repo https://github.com/calitb/temp

yes, it's probably because of latest expo. 

<img width="1210" alt="Captura de Pantalla 2022-08-31 a la(s) 4 41 31 p  m" src="https://user-images.githubusercontent.com/1728291/187790477-91d5d1f9-a481-4c5f-be90-902ab6ffb421.png">

**Comment by andrew-levy** [comment]
@calitb With the updates to `expo-modules-core` much of the Module API was changed, so I had to make a few more changes to support the most up to date api. I opened a [PR](https://github.com/andrew-levy/react-native-userdefaults/pull/3) to fix this. Just testing a little bit more and will release a new version after that.

**Comment by andrew-levy** [comment]
@calitb I just released v0.2.0 which should resolve this issue. Are you able to confirm that it works for you? Thanks again for pointing this out

**Comment by calitb** [comment]
working for me :)
